var localization = {
    RU: {
        men: [
            'Валерий Фе****',
            'Владислав Ко****',
            'Владимир Ма****',
            'Валентин Ди****',
            'Валерий Ще******',
            'Иван Ба*****',
            'Вячеслав Ку****',
            'Михаил Ро*****',
            'Сергей Во*****',
            'Дмитрий Де*****',
            'Вячеслав Шу****',
            'Дима Ав*****',
            'Денис Ми***',
            'Евгений Ма*****',
            'Виталий Ми****',
            'Даниил Те*****',
            'Влад Бу*****',
            'Иван Гр*****',
            'Алексей Ре*****',
            'Владимир Су****',
            'Вадим Тр*****',
            'Вадим Га*****',
            'Евгений Го****',
            'Евгений Ба****',
            'Сергей Жу***',
            'Влад Че*****',
            'Владислав Ни****',
            'Виктор Че*****',
            'Олег Як*****',
            'Дмитрий Гл*****',
            'Василий Кр****',
            'Антон За****',
            'Антон Бе****',
            'Илья Со****',
            'Сергей Ми****',
            'Дмитрий Да****',
            'Владислав Ра****',
            'Дмитрий Вл*****',
            'Иван Ма*****',
            'Павел Пр*****',
            'Никита Ки****',
            'Максим Ша*****',
            'Ярослав Ко****',
            'Илья См*****',
            'Андрей Ле****',
            'Андрей Ни*****',
            'Артём Ре****',
            'Анатолий Ти*****',
            'Ярослав За*****',
            'Василий Гу****'
        ],
        women: [
            'Анна Па*****',
            'Алина Ер*****',
            'Александра Ло****',
            'Елена Бы****',
            'Марина Ел****',
            'Анна Мо****',
            'Ксения Кр*****',
            'Алена Бо****',
            'Виктория Ка****',
            'Маргарита Бе****',
            'Анна Ры*****',
            'Дарья Са*****',
            'Алла Кр*****',
            'Евгения Ко****',
            'Антонина Пе****',
            'Ирина Со****',
            'Алена Во****',
            'Валентина Бу****',
            'Вика Др****',
            'Валерия Ло****',
            'Кристина Со****',
            'Наталья Го*****',
            'Марина Ма*****',
            'Катерина Ля****',
            'Анастасия Ле*****',
            'Екатерина Во*****',
            'Наталья Ло****',
            'Валентина Ля****',
            'Вероника Ан****',
            'Викуся Пр*****',
            'Мария Ша****',
            'Василиса Ма****',
            'Ольга Дм****',
            'Виктория Ни****',
            'Дарья Пе****',
            'Татьяна Ко****',
            'Валентина Ко****',
            'Оля Са******',
            'Лилия Ма*****',
            'Ирина Пе*****',
            'Анна Да*******',
            'Анастасия Во****',
            'Полина Гр****',
            'Мария Ко****',
            'Кристина До****',
            'Юлия Пу****',
            'Татьяна Ла****',
            'Валерия Лу****',
            'Анастасия Шп****',
            'Алёна Ши****'
        ],
        beforenametext: '',
        madeOrderOnSum: ', сделал(а) заказ на сумму ',
        wasOrdered: ', заказано ',
        left: ' Осталось упаковок',
        shared: ' по акции ',
        usersOnline: 'Количество посетителей на сайте: ',
        orderedCallback: ', сделал(а) заявку на обратный звонок',
        packsLeft: 'Осталось упаковок по акции ',
        codeEmpty: 'Введите, пожалуйста, код.',
        codeOk: 'Данный код верен. Cпасибо, что выбрали нашу продукцию!',
        codeWrong: 'К сожалению, данный код не найден! Вероятнее всего, вы приобрели поддельный продукт.',
        packName : ' шт.'
    },
    TL: {
        men: [
            'Nampong Nakorn',
            'Natwatcharaphon Samrong',
            'Atthophol Rostham',
            'Whatcharakorn Sonnuwat',
            'Sorrasak Tujinda',
            'Weerasuk Chimi Permphasook',
            'Phunaphot Ketlekha',
            'Phimrawi Ditthaneat',
            'Chayaphon Purathane',
            'Tik Jung',
            'Nuttapol Chuasart',
            'Passakon Yangsouy',
            'Wuthiphan Jojo Ungkubkeaw',
            'Jakkit Prachompol',
            'Khanong Yotarat',
            'Soisakul Paitoon',
            'Abhithan Limboriboon',
            'Siriphong Kasiphochana',
            'Apichat Daengkongkho',
            'Molakrai Wanachai',
            'Attapon Pantu',
            'Chalit Laknoy',
            'Aeknarin Reuangsamut',
            'Warayut Chaninsi',
            'Turbohuahin Rattananakin',
            'Ratithon Mark Chankomol',
            'Kriengkrai Wongngernpet',
            'Sanit Nitld Supjarussang',
            'Rungsun Meeprasart',
            'Somchai Paithumsut'
        ],
        women: [
            'Kantima Juicharoen',
            'Kawinthip Chanthaniyom',
            'Tippawan Lasonti',
            'Thanyathip Srisanyos',
            'Sunantha Phansawat',
            'Parngporn Chainarong',
            'Chaninrat Thongsri',
            'Watchara Imjai',
            'Panita Sornthian',
            'Warangkana Wongchompoo',
            'Baifern Natthaphatsorn',
            'Natchaya Wirojwatanakul',
            'Thidathip Noosing',
            'Vimwipa Klaviggarn',
            'Sasisumon Yangchumchuen',
            'Wilawan Kitcharoenwong',
            'Phachara Num Phusudsung',
            'Aew Junjira',
            'Trairat Wittayapreechaku',
            'Jantira Jamjaroen',
            'Saitharn Prasansee',
            'Aomaom Panisara Onnim',
            'Tripaporn Jantarawijit',
            'Numpeung Hongsakun',
            'Patcharadanai Kaewprasaet',
            'Roongnapa Pungpun',
            'Maneerat Manosansophon',
            'Phetcharat Charayut',
            'Rinrada Pairot',
            'Sudaporn Sonthong'
        ],
        beforenametext: 'คุณ ',
        madeOrderOnSum: ' ได้สั่งสินค้าเป็นจำนวนเงิน',
        wasOrdered: ' สั่งซื้อเรียบร้อยแล้ว ',
        left: ' มีสินค้าโปรโมชั่นเหลือ ',
        shared: ' กล่อง',
        usersOnline: 'จำนวนผู้เข้าชมเวปไซต์ ',
        orderedCallback: ' แจ้งให้เจ้าหน้าที่ติดต่อกลับเรียบร้อยแล้ว',
        packsLeft: 'มีสินค้าโปรโมชั่นเหลือ ',
        codeEmpty: 'กรุณาใส่รหัส',
        codeOk: 'รหัสสินค้าถูกต้อง ขอบคุณที่เลือกใช้ผลิตภัณฑ์ของเรา',
        codeWrong: 'ขออภัย ไม่พบรหัส เป็นไปได้ว่าสินค้าที่คุณซื้อไปอาจเป็นของปลอม',
        invalidNameText: 'กรุณาระบุชื่อที่ถูกต้อง',
        invalidPhoneText: 'กรุณาระบุหมายเลขโทรศัพท์ที่ถูกต้อง ไม่เช่นนั้นเราจะไม่สามารถติดต่อกับคุณได้',
        packName : ' กล่อง'

    },
    RO: {
        men: [
            'Stefan Ma****',
            'Brandusa Ione****',
            'Nicolae Gheor****',
            'Florin Rox****',
            'Catalin Pope****',
            'Ioan R****',
            'Adrian Constan****',
            'Mihai Cos****',
            'Dan P****',
            'Dumitru Ser****',
            'Gabriel Preoșe****',
            'Dumitru Poste****',
            'David B****',
            'Florin Namgale****',
            'Mircea Cov****',
            'Daniel O****',
            'Eugen Merin****',
            'Ioan Petr****',
            'Alexandru P****',
            'Lazar Ione****',
            'Brandușa Gheor****',
            'Dorin Merin****',
            'Eduard Ma****',
            'Neculai Mazile****',
            'Lucian Merin****',
            'Matei Pope****',
            'Gabriel Petr****',
            'Mircea Curcan****',
            'Adrian R****',
            'Dumitru Constan****',
            'Vasile S****',
            'Dorin M****',
            'Miron Brașovi****',
            'Ionuț Anghe****',
            'Iustin Cojoc****',
            'Dumitru Cojoca****',
            'Ignat Cozme****',
            'Dumitru Mi****',
            'Ioan Pe****',
            'Florentin Pope****',
            'Constantin Catar****',
            'Matei Car****',
            'Gabriel Ig****',
            'Ion Constan****',
            'Andrei Ser****',
            'Andrei Gheor****',
            'Eugen P****',
            'Brandusa Chirileanu',
            'Miron Ione****',
            'Vasile Ma****',
            'Alexandru Mazile****',
            'Gheorghe Grosu'
        ],
        women: ['Ana Pope****',
            'Floarea Mazile****',
            'Andreea Chirile****',
            'Elena Andr****',
            'Mariana Ione****',
            'Ana Mir****',
            'Marina Poste****',
            'Elena Oroș****',
            'Alina Go****',
            'Mariana Gheor****',
            'Ana Constan****',
            'Alexandra S****',
            'Cristina Ma****',
            'Ioana P****',
            'Andreea Chir****',
            'Aglaia Maco****',
            'Elena And****',
            'Georgiana ****',
            'Mihaela R****',
            'Felicia R****',
            'Carolina Munte****',
            'Horea Ser****',
            'Mariana Insura****',
            'Felicia Ione****',
            'Dana Ra****',
            'Ioana Ha****',
            'Dorina Pope****',
            'Eleonora Cu****',
            'Viorica Chirilean****',
            'Alexandra P****',
            'Maria Dimo****',
            'Viorica Timo****',
            'Ioana Paval****',
            'Aglaia Pavl****',
            'Denisa Cojoc****',
            'Doina Mo****',
            'Monica Gheor****',
            'Magda Ma****',
            'Floarea Pope****',
            'Alina Ione****',
            'Ana Mazile****',
            'Ana-Maria R****',
            'Denisa Mor****',
            'Maria Ser****',
            'Georgiana Craiove****',
            'Camelia S****',
            'Magdalena Constan****',
            'Viorica Țep****',
            'Ana-Maria Lepa****',
            'Elena B****',
        ],
        beforenametext: '',
        madeOrderOnSum: ', un ordin pentru suma de ',
        wasOrdered: ', au comandat ',
        left: 'Au ramas ',
        shared: ' pe reducere ',
        usersOnline: 'Numărul de vizitatori ai site-ului: ',
        orderedCallback: ', a făcut o cerere pentru un apel de retur',
        packsLeft: 'Au ramas cutii pe reducere ',
        codeEmpty: 'Scrieți vă rog, codul.',
        codeOk: 'Acest cod este drept. Mulțumesc că ați ales producția noastră.',
        codeWrong: 'Cu părere de rău acest cod nu poate fi găsit! Cel mai probabil, ați cumpărat un produs contrafăcut.',
        packName : ' cutii' 
    }
}

/* Доп функция */
String.prototype.replaceAt = function(index, character) {
        return this.substr(0, index) + character + this.substr(index + character.length);
    }

/* Добавляем звездочки */
function addStars(arr) {
    for (var i = 0; i < arr.length; i++) {
        var trimName = arr[i];
        var startStars = trimName.indexOf(' ') + 3;
        var cutStr = trimName.slice(0, startStars);
        var newItem = cutStr.replaceAt(startStars, "*****");
        arr.splice(i, 1, newItem);
    }
}

function concatMenAndWoman(arr1, arr2) {
    var concatedArray = arr1.concat(arr2);
    addStars(concatedArray);
    return concatedArray;
}

function setLocalization(localiz) {
   
    if (genderNames == 'men') {
        nameList = concatMenAndWoman(localization[localiz].men, []);
    } else if (genderNames == 'women') {
        nameList = concatMenAndWoman(localization[localiz].women, []);
    } else {
        nameList = concatMenAndWoman(localization[localiz].men, localization[localiz].women);
    }
    beforenametext = localization[localiz].beforenametext;
    madeOrderOnSum = localization[localiz].madeOrderOnSum;
    wasOrdered = localization[localiz].wasOrdered;
    left = localization[localiz].left;
    shared = localization[localiz].shared;
    usersOnline = localization[localiz].usersOnline;
    orderedCallback = localization[localiz].orderedCallback;
    packsLeft = localization[localiz].packsLeft;
    codeEmpty = localization[localiz].codeEmpty;
    codeOk = localization[localiz].codeOk;
    codeWrong = localization[localiz].codeWrong;
    packName = localization[localiz].packName;
}

setLocalization(countryCodeLocation);

